### ISSUE TITLE
convert bootstrap design to custom design 

### ISSUE THREAD

**Issue by HemendraKhatik** [HemendraKhatik/FlackApp#40]
this website is built with bootstrap and I want someone to convert bootstrap to custom CSS.

#### points to keep in mind

- use flexbox for grid design
- use vh and % units for padding, margin, height and width.
- design should be mobile responsive

### Feel free to be creative in designing

**Comment by DaywisonSilva** [comment]
Hello, can I have this?

**Comment by Akshansh99** [comment]
Can you assign me this?

**Comment by cSparkle** [comment]
Hello! I'm interested in taking on this task. 

Do you have any ideas in mind for the finished product or a color palette you like?
Thanks!

**Comment by HemendraKhatik** [comment]
> Hello! I'm interested in taking on this task.
> 
> Do you have any ideas in mind for the finished product or a color palette you like?
> Thanks!

sure @cSparkle  and well I like the variations of blue, black and white colors you can get the color palettes from [this](https://colorsinspo.com/) website

**Comment by cSparkle** [comment]
@HemendraKhatik awesome! I'll get started soon!

**Comment by cSparkle** [comment]
@HemendraKhatik Could you help me out with creating the proper DB? I'm less familiar with Flask and Python migrations and I'm not sure which command to run to create the DB and run the migrations properly.

**Comment by HemendraKhatik** [comment]
> @HemendraKhatik Could you help me out with creating the proper DB? I'm less familiar with Flask and Python migrations and I'm not sure which command to run to create the DB and run the migrations properly.

@cSparkle Just go through the **readme.MD**  file again I've made a few changes. This time it will be easier for you to run this.

**Comment by HemendraKhatik** [comment]
@cSparkle can you please make a pull request again? since I've cleaned the code and introduce a new way to run this app locally.

**Comment by cSparkle** [comment]
> @cSparkle can you please make a pull request again? since I've cleaned the code and introduce a new way to run this app locally.

Will do! Thanks for letting me know 😁

**Comment by cSparkle** [comment]
Hey @HemendraKhatik! I hadn't gotten far before you made those code changes, so I reforked and reinstalled everything. 

I'm getting the following error when I run `python create.py`:

```
Traceback (most recent call last):
  File "create.py", line 3, in <module>
    from flask import Flask, render_template, request
ImportError: No module named flask
```

I tried installing Flask manually using `pip install flask`, but I got the same error. I think it might be a problem somewhere in the code.

**Comment by HemendraKhatik** [comment]
> Hey @HemendraKhatik! I hadn't gotten far before you made those code changes, so I reforked and reinstalled everything.
> 
> I'm getting the following error when I run `python create.py`:
> 
> ```
> Traceback (most recent call last):
>   File "create.py", line 3, in <module>
>     from flask import Flask, render_template, request
> ImportError: No module named flask
> ```
> 
> I tried installing Flask manually using `pip install flask`, but I got the same error. I think it might be a problem somewhere in the code.

Run these lines in your python interpreter to confirm flask is installed successfully
>> import flask
>> flask.__version__

it should return the flask package version.

**Comment by cSparkle** [comment]
@HemendraKhatik ahh, got it working! Turns out to have been a verison mismatch with Python. Thanks for the guidance!

**Comment by cSparkle** [comment]
Hi @HemendraKhatik! I finished up converting everything from Bootstrap to vanilla css for the login page. Before I do the rest of the app, I wanted to show you what I had to make sure I was on the right track in terms of design. Let me know what you think!

![Screen_Recording_2020-10-08_at_11 35 21_AM](https://user-images.githubusercontent.com/42003899/95481139-ac753080-095a-11eb-9fd3-e167081fd7b4.gif)

**Comment by HemendraKhatik** [comment]
@cSparkle Awesome, better than before. keep it up.

### Point to keep in mind

-  Feel free to be more creative.
- If you think something is lacking just introduce one.
- if you think something is unnecessary remove it (after discussion).

For any discussion, you can shoot an email at sendtohemendra@gmail.com.
